#!/usr/bin/env python3
"""Regenerate .github/PIPELINE.md with a Mermaid diagram of .github/workflows/*.yml.

Run manually with `python3 scripts/generate_pipeline_diagram.py`, or let the
"Pipeline diagram" GitHub Action run it whenever a workflow file changes.
"""
import pathlib
import re

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = ROOT / ".github" / "workflows"
OUTPUT = ROOT / ".github" / "PIPELINE.md"
SELF_WORKFLOW = "pipeline-diagram.yml"


def sanitize(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]", "_", name)


def trigger_labels(on) -> list[str]:
    # PyYAML resolves the unquoted `on:` key itself to the boolean True,
    # which callers must account for before reaching this function.
    if isinstance(on, str):
        return [on]
    if isinstance(on, list):
        return [str(t) for t in on]
    if isinstance(on, dict):
        labels = []
        for name, cfg in on.items():
            if isinstance(cfg, dict) and cfg.get("types"):
                labels.append(f"{name} ({', '.join(cfg['types'])})")
            else:
                labels.append(str(name))
        return labels
    return ["?"]


def workflow_block(path: pathlib.Path) -> tuple[str, list[str]] | None:
    try:
        data = yaml.safe_load(path.read_text())
    except yaml.YAMLError as exc:
        wf_id = sanitize(path.stem)
        return wf_id, [
            f'  subgraph {wf_id} ["{path.name} (INVALID YAML)"]',
            f'    {wf_id}_err["parse error: {str(exc).splitlines()[0]}"]:::error',
            "  end",
        ]

    wf_name = data.get("name", path.stem)
    wf_id = sanitize(path.stem)
    on = data.get(True, data.get("on", {}))
    triggers = " / ".join(trigger_labels(on))

    lines = [f'  subgraph {wf_id} ["{wf_name}"]']
    trig_id = f"{wf_id}_trigger"
    lines.append(f'    {trig_id}(["{triggers}"])')

    for job_id, job in (data.get("jobs") or {}).items():
        node_id = f"{wf_id}_{sanitize(job_id)}"
        step_count = len(job.get("steps") or [])
        label = f"{job_id}\\n{step_count} steps"
        env = job.get("environment")
        env = env.get("name") if isinstance(env, dict) else env
        open_c, close_c = "[", "]"
        style = ""
        if env:
            open_c, close_c = "{{", "}}"
            label += f"\\n\u23f8 {env}"
            style = f"    class {node_id} gated;"
        lines.append(f'    {node_id}{open_c}"{label}"{close_c}{(chr(10) + style) if style else ""}')

        needs = job.get("needs")
        if needs:
            needs = [needs] if isinstance(needs, str) else needs
            for n in needs:
                lines.append(f"    {wf_id}_{sanitize(n)} --> {node_id}")
        else:
            lines.append(f"    {trig_id} --> {node_id}")

    lines.append("  end")
    return wf_id, lines


def build_mermaid() -> str:
    lines = [
        "flowchart LR",
        "  classDef gated fill:#d98e4a22,stroke:#d98e4a,stroke-width:2px;",
        "  classDef error fill:#e2665b22,stroke:#e2665b,stroke-width:2px;",
    ]
    for path in sorted(WORKFLOWS_DIR.glob("*.yml")):
        if path.name == SELF_WORKFLOW:
            continue
        result = workflow_block(path)
        if result is None:
            continue
        _, block = result
        lines.extend(block)
    return "\n".join(lines)


def main() -> None:
    mermaid = build_mermaid()
    content = (
        "<!-- Auto-generated by scripts/generate_pipeline_diagram.py — do not edit by hand. -->\n"
        "# CI/CD pipeline\n\n"
        "Diagram of every workflow in `.github/workflows/`, regenerated on each change "
        "by the `Pipeline diagram` action. Hexagon nodes gate on a required-reviewer "
        "environment (\u23f8).\n\n"
        f"```mermaid\n{mermaid}\n```\n"
    )
    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
